name = "IndexSpaces"
uuid = "3ceaaf38-e7b4-4193-a23a-303dd231a83a"
version = "1.10.0"
authors = ["Erik Schnetter <schnetter@gmail.com>"]

[deps]
BFloat16s = "ab4f0b2a-ad5b-11e8-123f-65d77653426b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CUDASIMDTypes = "ba1ee33b-8807-41fd-9812-6d5f2ce04139"

[compat]
BFloat16s = "0.6.1"
CUDA = "3.12.0, 4, 5"
CUDASIMDTypes = "1.9.0"
julia = "1.10"
